'use strict';
const ROLES = { SUPER_ADMIN: 'SUPER_ADMIN', USER: 'USER' };

const ORDER_STATUS = {
  PENDING: 'pending', PAID: 'paid', SHIPPED: 'shipped',
  DELIVERED: 'delivered', CANCELLED: 'cancelled', REFUNDED: 'refunded',
};

const REFUND_STATUS = { PENDING: 'pending', APPROVED: 'approved', REJECTED: 'rejected' };

const PAYMENT_STATUS = { PENDING: 'pending', COMPLETED: 'completed', FAILED: 'failed', REFUNDED: 'refunded' };

const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN', LOGOUT: 'LOGOUT',
  PRODUCT_CREATE: 'PRODUCT_CREATE', PRODUCT_UPDATE: 'PRODUCT_UPDATE', PRODUCT_DELETE: 'PRODUCT_DELETE',
  STOCK_UPDATE: 'STOCK_UPDATE', PRICE_UPDATE: 'PRICE_UPDATE',
  ORDER_STATUS_CHANGE: 'ORDER_STATUS_CHANGE',
  REFUND_APPROVE: 'REFUND_APPROVE', REFUND_REJECT: 'REFUND_REJECT',
  COUPON_CREATE: 'COUPON_CREATE', COUPON_UPDATE: 'COUPON_UPDATE',
};

module.exports = { ROLES, ORDER_STATUS, REFUND_STATUS, PAYMENT_STATUS, AUDIT_ACTIONS };
